// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using My.Company;
#pragma warning restore 0105

namespace My.Company
{
    public static partial class Interop
    {
        public const string NativeLib = "akatsuki_pp";

        static Interop()
        {
        }


        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "calculate_score")]
        public static extern CalculateResult calculate_score(string beatmap_path, uint mode, uint mods, uint max_combo, double accuracy, uint miss_count);

    }

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CalculateResult
    {
        public double pp;
        public double stars;
    }



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error): base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
