// Automatically generated by Interoptopus.

#ifndef akatsuki_pp
#define akatsuki_pp

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>




typedef struct calculateresult
    {
    double pp;
    double stars;
    } calculateresult;


calculateresult calculate_score(const char* beatmap_path, uint32_t mode, uint32_t mods, uint32_t max_combo, double accuracy, uint32_t miss_count);


#ifdef __cplusplus
}
#endif

#endif /* akatsuki_pp */
